"""Tests for cross-reference classification.

The graph feeds multi-hop ground truth, so a false internal edge is the failure
this component exists to prevent. Each failure mode found during development is
pinned here as a regression test using the actual text that produced it, so a
future refactor cannot quietly reintroduce it.

Precision is the property under test throughout. Recall is deliberately
sacrificed, so tests assert that doubtful references are dropped, not kept.
"""

from __future__ import annotations

import pytest

from src.ingest.xref import (
    amends_external_instrument,
    extract_references,
    external_instruments_in,
)

DOC = "eu_ai_act"


def internal_of(text: str, **kwargs) -> list[str]:
    return extract_references(text, DOC, **kwargs)[0]


def dropped_of(text: str, **kwargs) -> list[str]:
    return [d["ref"] for d in extract_references(text, DOC, **kwargs)[2]]


# --------------------------------------------------------------------------
# Baseline behaviour
# --------------------------------------------------------------------------

def test_an_unqualified_reference_is_internal():
    text = "The risk management system referred to in Article 9 shall be taken into account."
    assert internal_of(text) == ["eu_ai_act:art_9"]


def test_an_annex_reference_is_internal():
    text = "AI systems referred to in Annex III shall be considered to be high-risk."
    assert internal_of(text) == ["eu_ai_act:anx_III"]


def test_a_subsection_reference_resolves_to_its_article():
    text = "the logs referred to in Article 12(1), automatically generated by the system."
    assert internal_of(text) == ["eu_ai_act:art_12"]


def test_an_explicit_external_qualifier_is_not_internal():
    text = "as defined in Article 3, point 19 of Regulation (EU) 2019/1020, in so far as they present."
    assert internal_of(text) == []


def test_a_range_is_expanded_to_its_members():
    text = "The procedures referred to in Articles 79 to 83 shall not apply."
    assert internal_of(text) == [f"eu_ai_act:art_{n}" for n in range(79, 84)]


def test_an_enumeration_captures_every_member():
    text = "the requirements referred to in Articles 16 and 114 shall apply."
    assert internal_of(text) == ["eu_ai_act:art_114", "eu_ai_act:art_16"]


# --------------------------------------------------------------------------
# Regression: Mode A, bare references inside an article amending another act
# --------------------------------------------------------------------------

ART_108_TEXT = (
    "Article 108 Amendments to Regulation (EU) 2018/1139\n"
    "Regulation (EU) 2018/1139 is amended as follows:\n"
    "(1) in Article 17, the following paragraph is added: '3. Without prejudice to paragraph 1.'\n"
    "(3) in Article 43, the following paragraph is added: '4. When adopting implementing acts.'\n"
    "(4) in Article 47, the following paragraph is added: '3. When adopting delegated acts.'\n"
    "(5) in Article 57, the following subparagraph is added: 'When adopting those acts.'\n"
    "(6) in Article 58, the following paragraph is added: '3. When adopting delegated acts.'"
)


def test_mode_a_amending_article_emits_no_internal_edges():
    """art_108's bare references are to Regulation 2018/1139, not to this Act."""
    internal = internal_of(ART_108_TEXT, amends_external=True)
    for number in (17, 43, 47, 57, 58):
        assert f"eu_ai_act:art_{number}" not in internal


def test_mode_a_drops_are_recorded_with_a_reason():
    dropped = extract_references(ART_108_TEXT, DOC, amends_external=True)[2]
    assert dropped, "drops must be recorded, not silently discarded"
    assert all("amending an external instrument" in d["reason"] for d in dropped)
    assert all(d["sentence"] for d in dropped)


def test_mode_a_heading_detection_distinguishes_the_two_kinds_of_amendment():
    assert amends_external_instrument("Amendments to Regulation (EU) 2018/1139")
    assert amends_external_instrument("Amendment to Directive 2014/90/EU")
    # art_7 amends THIS Act, so it must not be treated as an external scope.
    assert not amends_external_instrument("Amendments to Annex III")


def test_mode_a_fix_does_not_over_trigger_on_article_7():
    """art_7 amends this Act's own Annex III, so its edges stay internal."""
    text = (
        "The Commission is empowered to adopt delegated acts in accordance with Article 97 "
        "to amend Annex III by adding or modifying use-cases of high-risk AI systems."
    )
    internal = internal_of(text, amends_external=amends_external_instrument("Amendments to Annex III"))
    assert "eu_ai_act:anx_III" in internal
    assert "eu_ai_act:art_97" in internal


# --------------------------------------------------------------------------
# Regression: Mode B, anaphoric instrument, "that Regulation"
# --------------------------------------------------------------------------

def test_mode_b_that_regulation_is_not_internal():
    """rct_149: the instrument is named in the previous sentence."""
    text = (
        "The Commission should make use of Article 30 of Regulation (EU) 2019/1020. "
        "In accordance with Article 33 of that Regulation, the Commission should support "
        "the activities of the authorities."
    )
    assert "eu_ai_act:art_33" not in internal_of(text)


def test_mode_b_variants_of_anaphora_are_caught():
    for phrase in ("that Regulation", "the said Regulation", "the same Directive"):
        text = f"In accordance with Article 33 of {phrase}, the Commission shall act."
        assert internal_of(text) == [], phrase


def test_this_regulation_is_still_recognised_as_internal():
    text = "the prohibition of the AI practices referred to in Article 5 of this Regulation."
    assert internal_of(text) == ["eu_ai_act:art_5"]


# --------------------------------------------------------------------------
# Regression: Mode C, one qualifier distributed across an enumeration
# --------------------------------------------------------------------------

def test_mode_c_distributed_qualifier_drops_the_leading_reference():
    """rct_140: 'of Directive 2016/680' governs both references, not just the last."""
    text = (
        "and without prejudice to Article 4(2) and Article 10 of Directive (EU) 2016/680. "
        "All other obligations remain."
    )
    internal = internal_of(text)
    assert "eu_ai_act:art_4" not in internal
    assert "eu_ai_act:art_10" not in internal


# --------------------------------------------------------------------------
# Regression: Mode D, instruments named by acronym, found by the full audit
# --------------------------------------------------------------------------

@pytest.mark.parametrize(
    "text, absent",
    [
        ("it is appropriate to base this Regulation on Article 16 TFEU.", "eu_ai_act:art_16"),
        ("national security remains the responsibility of Member States under Article 4(2) TEU.",
         "eu_ai_act:art_4"),
        ("the power to adopt acts in accordance with Article 290 TFEU should be delegated.",
         "eu_ai_act:art_290"),
    ],
)
def test_mode_d_acronym_instruments_are_not_internal(text, absent):
    assert absent not in internal_of(text)


def test_acronyms_are_detected_as_instrument_mentions():
    assert external_instruments_in("in accordance with Article 4(2) TEU and by the nature") == ["TEU"]


# --------------------------------------------------------------------------
# Precedence and conservatism
# --------------------------------------------------------------------------

def test_explicit_self_qualification_outranks_a_competing_instrument():
    """anx_VIII names Directive 2016/680 yet qualifies its own reference explicitly."""
    text = (
        "A summary of the data protection impact assessment carried out in accordance with "
        "Article 35 of Regulation (EU) 2016/679 or Article 27 of Directive (EU) 2016/680 "
        "as specified in Article 26(8) of this Regulation, where applicable."
    )
    internal = internal_of(text)
    assert internal == ["eu_ai_act:art_26"]


def test_a_competing_instrument_in_the_sentence_drops_an_unqualified_reference():
    text = (
        "This Regulation shall not affect Regulation (EU) 2016/679, without prejudice to "
        "Article 10(5) and Article 59."
    )
    assert internal_of(text) == []
    assert "eu_ai_act:art_10" in dropped_of(text)


def test_the_act_referring_to_itself_by_number_is_not_an_external_instrument():
    assert external_instruments_in("as set out in Regulation (EU) 2024/1689") == []


def test_lowercase_decisions_is_not_an_instrument_mention():
    """EU drafting capitalises instrument nouns; the common word must not fire."""
    assert external_instruments_in("deployers that make decisions or assist in making decisions") == []
    assert external_instruments_in("based on a decision of the Commission") == []


def test_capitalised_decision_is_an_instrument_mention():
    assert external_instruments_in("Article R23 of Annex I to Decision No 768/2008/EC") == ["Decision"]


def test_every_drop_carries_a_reason_and_its_sentence():
    _, _, dropped, _ = extract_references(
        "This Regulation shall not affect Regulation (EU) 2016/679, without prejudice to Article 59.",
        DOC,
    )
    assert dropped
    for record in dropped:
        assert record["reason"]
        assert record["sentence"]
        assert record["ref"].startswith("eu_ai_act:")
